# Generated by Django 3.2.23 on 2024-01-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='phone',
            new_name='password',
        ),
    ]
